---
title: "NMscanData: Find And Combine All Output And Input Data"
output:
rmarkdown::html_vignette:
    toc: true
Suggests: markdown
VignetteBuilder: knitr
vignette: >
  %\VignetteIndexEntry{NMscanData: Find and combine all output and input data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
header-includes:
- \usepackage{ae}
---

```{r, include = FALSE}
##knitr::opts_chunk$set(dev = "cairo_pdf")
knitr::opts_chunk$set(
                      collapse = TRUE
                     ,comment = "#>"
                     ,fig.width=7
                     ,cache=FALSE
                  )

## this change data.table syntax. I think we can do without.
## knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60), tidy=TRUE)
```

Built `r Sys.Date()` using NMdata `r packageVersion("NMdata")`.

This vignette is still under development. Please make sure to see latest version available [here](https://philipdelff.github.io/NMdata/).


::: columns
:::: column
### Basics
general,NMdataConf,Configure default behavior of NMdata functions

### Data set generation


dataCreate,compareCols,Compare presence and classes of columns across data sets before merge or rbind
dataCreate,renameByContents,Rename columns based on contents
dataCreate,mergeCheck,Verify that the rows that come out of the merge are the exact same as in one of the existing datasets
dataCreate,flagsAssign,Assign exclusion flags to a dataset based on specified table
dataCreate,flagsCount,Create an overview of number of retained and discarded datapoints
dataCreate,NMorderColumns,Standardize column order in Nonmem input data

::::

:::: column

### Read from and edit Nonmem control streams
Nonmem,NMreadSection,Extract sections of Nonmem control streams
Nonmem,NMwriteSection,Replace sections of a nonmem control stream

### Retrieve Nonmem results
DataRead,NMscanData,Automatically find Nonmem input and output tables and organize data
DataRead,NMscanTables,Find and read all output data tables in nonmem run
DataRead,NMreadTab,Read an output table file from NONMEM
DataRead,NMscanInput,Find and read input data and optionally translate column names according to the $INPUT section
DataRead,NMreadCsv,Read input data formatted for nonmem
DataRead,NMinfo,Get metadata from an NMdata object

::::

:::: column
### Debugging Nonmem and input data
debug,NMcheckColnames,Compare $DATA to column names in input data


### Programming
egdt
misc,findCovs,Extract columns that do not vary within values of other columns
misc,findVars,Extract columns that vary within values of other columns



::::
:::

