* NMdata todo
** Design 
*** TODO For a version 0.2.0, omit the extra variability levels
just provide functions to get them
*** TODO Allow for say input.txt/output.txt
**** NMtransInput
** Function improvements
*** NMextractText
**** TODO reduce lines and text to one argument
The information is sufficient when taking into account the linesep
arguement. If length(lines) and linesep is given, a warning must be
issued.
*** NMtransInput
**** DONE Names of variables must be taken from lst, not mod
     CLOSED: [2020-06-06 Sat 23:43]
mod should only be used for path to dataset.
**** DONE Add support for absolute paths
     CLOSED: [2020-06-09 Tue 23:22]
**** TODO SKIP like DROP
**** TODO TIME and related columns
I still don't really understand the documentation on this, but it doesnt seem
too hard to implement. It should NOT only be interpreted when the A=B format is used in
$INPUT. If something is called TIME, it must be checked for format.
*** NMtransFilters
**** TODO Replace single = with ==
According to the manual single = can be used for comparisons. This is not and
should not be translated by NMcode2R.
**** TODO $INPT is an alias for $INPUT
