##' Read an output table file from Nonmem
##'
##' Read a table generated by a $TABLE statement in Nonmem. Generally,
##' these files cannot be read by read.table or similar because
##' formatting depends on options in the $TABLE statement, and because
##' Nonmem sometimes includes extra lines in the output that have to
##' be filtered out. NMreadTab can do this automatically based on the
##' table file alone.
##'
##' @param file path to Nonmem table file
##' @param col.tableno In case of simulations where tables are being
##'     repeated, a counter of the repetition number can be useful to
##'     include in the output. For now, this will only work if the
##'     NOHEADER option is not used. This is because NMreadTab
##'     searches for the "TABLE NO..." strings in Nonmem output
##'     tables. If col.tableno is TRUE (default), a counter of tables
##'     is included as a column called NMREP. Notice, the table
##'     numbers in NMREP are cumulatively counting the number of
##'     tables reported in the file. NMREP is not the actual table
##'     number as given by Nonmem.
##' @param col.table.name The name of a column containing the name or
##'     description of the table (generated by Nonmem). The default is
##'     "table.name". Use FALSE not to include this column.
##' @param header Use header=FALSE if table was created with NOHEADER
##'     option in $TABLE.
##' @param skip The number of rows to skip. The default is skip=1 if
##'     header==TRUE and skip=0 if header==FALSE.
##' @param quiet logical stating whether or not information is printed
##'     about what is being done. Default can be configured using
##'     NMdataConf.
##' @param as.fun The default is to return data as a data.frame. Pass
##'     a function (say tibble::as_tibble) in as.fun to convert to
##'     something else. If data.tables are wanted, use
##'     as.fun="data.table". The default can be configured using
##'     NMdataConf.
##' @param ... Arguments passed to fread.
##' @return The Nonmem table data.
##' @details The actual reading of data is based on
##'     data.table::fread. Generally, the function is fast thanks to
##'     data.table.
##' @import data.table
##' @family DataRead
##' @export


NMreadTab <- function(file,col.tableno,col.table.name,header=TRUE,skip,quiet=TRUE,as.fun,...) {
    
#### Section start: Dummy variables, only not to get NOTE's in pacakge checks ####

    TABLE <- NULL
    NMREP <- NULL

### Section end: Dummy variables, only not to get NOTE's in pacakge checks

### todo: Keep track of whether to keep col.tableno and col.table.name

    if(missing(col.tableno) || is.null(col.tableno) || isTRUE(col.tableno) ){
        col.tableno <- "TABLE.NO"
    }
    rm.col.tableno <- FALSE
    if(isFALSE(col.tableno)){
        col.tableno <- "TABLE.NO"
        rm.col.tableno <- TRUE
    }

    if(missing(col.table.name) || is.null(col.table.name) || isTRUE(col.table.name) ){
        col.table.name <- "table.name"
    }

    rm.col.table.name <- FALSE
    if(isFALSE(col.table.name)){
        col.table.name <- "table.name"
        rm.col.table.name <- TRUE
    }
    
    ## arg checks
    if(!is.character(file)) stop("file should be a character string",call.=FALSE)
    if(!file.exists(file)) stop("argument file is not a path to an existing file.",call.=FALSE)

    if(missing(as.fun)) as.fun <- NULL
    as.fun <- NMdataDecideOption("as.fun",as.fun)

    if(missing(quiet)) quiet <- NULL
    quiet <- NMdataDecideOption("quiet",quiet)

    if(missing(skip)){
        skip <- 1
### Not sure this is correct. Are header and "TABLE" printing options related?
        if(!header) skip <- 0
    }
    dt1 <- fread(file,fill=TRUE,header=header,skip=skip,...)
    
    cnames <- colnames(dt1)
    if(!quiet){
        message("Adding table numbers to data")
    }
    
    ## if(col.tableno){
    ##     ## find table numbers
    ##     dt1[grep("^TABLE",as.character(get(cnames[1])),invert=FALSE,perl=TRUE),TABLE:=get(cnames[1])]
    ##     if(header){
    ##         dt1[,NMREP:=cumsum(!is.na(TABLE))+1]
    ##     }
    ##     dt1[,TABLE:=NULL]
    ## }

    ## if(col.tableno){
    ## find table numbers
    col.row.tmp <- tmpcol(dt1)
    dt1[,(col.row.tmp):=.I]
    dt1[grep("^TABLE",as.character(get(cnames[1])),invert=FALSE,perl=TRUE),(col.table.name):=paste(unlist(.SD),collapse=" "),by=col.row.tmp]
    dt1[,(col.row.tmp):=NULL]
    if(skip==1){
        title.tab1 <- readLines(file,n=1)
        dt1[1,(col.table.name):=title.tab1]
    }
    if(header){
        
        dt1[,(col.tableno):=cumsum(!is.na(get(col.table.name)))]
        ## }
#### todo: avoid zoo dependency by merging table.name findings by (col.tableno)
        ##dt1[,(col.table.name):=na.locf(get(col.table.name),na.rm=FALSE)]
        ## dt1 <- mergeCheck(dt1[,!(col.table.name) ,with=FALSE],
        ##                   unique(dt1[!is.na(get(col.table.name)),c(col.tableno,col.table.name),with=FALSE])
        ##                  ,by=col.tableno,quiet=TRUE)
        ## dt1[,uniquePresent(get(col.table.name)),by=col.table.name]
        dt1[,(col.table.name):=get(col.table.name)[!is.na(get(col.table.name))],by=col.tableno]
        
        ## dt1[,(col.table.name):=na.locf(get(col.table.name),na.rm=FALSE)]
        ## dt1[,TABLE:=NULL]
    }
    
    if(!quiet){
        message("getting rid of non-data rows")
    }
    dt1 <- dt1[grep("^ *[[:alpha:]]",as.character(get(cnames[1])),invert=TRUE,perl=TRUE)]

    cols.dup <- duplicated(colnames(dt1))
    if(any(cols.dup)){
        messageWrap(paste0("Cleaned duplicated column names: ",paste(colnames(dt1)[cols.dup],collapse=",")),fun.msg=message)
        dt1 <- dt1[,unique(cnames),with=FALSE]
        
    }


    if(rm.col.table.name) dt1[,(col.table.name):=NULL]
    if(rm.col.tableno) dt1[,(col.tableno):=NULL]
    
    ## columns added and clened since cnames was created.
    cnames <- setdiff(colnames(dt1),c(col.table.name,col.tableno))
    dt1[,(cnames):=lapply(.SD,as.numeric),.SDcols=cnames]

    
    dt1 <- as.fun(dt1)
    
    return(dt1)
}
